### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#10]
Show all data from the registration

**Comment by eliaskousk** [comment]
I have a lot of existing boilerplate code on how to edit user's profile, view details, change password etc using the FOSUserBundle that is also used here at LibreCores. So I can work on this after I'm done with the organizations part, unless of-course it is already done by then!

**Comment by imphil** [comment]
Resolved in c523e35ad17214294c08c39a4eff20562f2f32dd
