### ISSUE TITLE
Make CSS in Roadmap more mobile-friendly

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#106]
Currently the CSS styling the images next to the text on http://librecores.devel/static/about#roadmap is a bit broken for mobile. 

![grafik](https://cloud.githubusercontent.com/assets/1467123/22404486/01214934-e632-11e6-9042-a73f8da0a4be.png)

Use a list with custom "bullets", or the col-XXX classes from bootstrap?

@berndca any input, or can you even have a look at that?

**Comment by berndca** [comment]
It seems that this page was created from Markdown? The styles are hard coded. How would we go about introducing classes here? I would use the same approach as for the front page:

```html
<div class="row">
	<div class="col-fa-3x">
		<i class="fa fa-share-alt fa-3x" aria-hidden="true"></i>
	</div>
	<div class="col-xs-12 col-offset-fa-3x">
		<div class="row">
		Share IP cores. Share knowledge. Share the fun of free and open digital hardware design.
		<a class="librecores-home-showcase-link-xs" href="{{ path('librecores_project_repo_project_new') }}">
» Add a project
</a></div>
	</div>
</div>
```

We should probably find a more generic name for the classes...

**Comment by imphil** [comment]
Oh, I should have mentioned that. The page comes from https://github.com/librecores/librecores-web/blob/master/site/sitecontent/about.md Classes certainly would be the way to go.

**Comment by wallento** [comment]
Yes, sorry for being hacky there :(
