### ISSUE TITLE
Add styled 404 page

### ISSUE THREAD

**Issue by berndca** [librecores/librecores-web#109]
The server currently responds with it's default bare bone 404 page when the requested page does not exist. This should be replaced by a custom page with some navigation so that user can easily find existing the pages.

Somebody needs to tell Symfony about the custom page before we can work on it. Otherwise it will never show up.

**Comment by imphil** [comment]
You just need to put the templates in a special directory, see here: https://symfony.com/doc/2.8/controller/error_pages.html#use-default-exception-controller
You can take the defaults from app/Resources/TwigBundle/views/Exception/ as starting point.

**Comment by imphil** [comment]
This bug has been marked as a "good first bug". If you're interested in working on it, have a look at the developer documentation at http://librecores-web.readthedocs.io/en/latest/ and comment on this bug or contact the listed mentor for more details. The mentor will be available to help you complete this task.

Mentor: @imphil
Required Skills: HTML, CSS

**Comment by Agathver** [comment]
Hello @imphil,
I'm new to librecores-web development. I'm working to resolve this issue. I am implementing, 400, 404 and 500 error pages.

**Comment by wallento** [comment]
Thanks @Agathver, looking forward to your code!

**Comment by imphil** [comment]
Fixed in #132
