### ISSUE TITLE
README from external sources should be synced and non-editable

### ISSUE THREAD

**Issue by wallento** [librecores/librecores-web#116]
I agree to a point raised by @berndca in #41 and that I missed so far:

- The description should be either freely editable or from an external source
- Text from an external source should probably be synced (by using the Github/Bitbucket/.. API hooks) or fetching periodically

The should be non-editable with a box saying why and a red button saying "I want to edit and make it become a free text" or so.

Any cons?

**Comment by wallento** [comment]
Looking at the appearance of the current page we should have a confirmation when switching from the first radio button ("Extract the project description out of the README file in the source code.") to the second ("Enter the project description here."), right?

**Comment by imphil** [comment]
I don't see how the current design is ambiguous to users. There are two clearly labeled choices. If there is anything unclear, please open a PR with a suggestion.

**Comment by wallento** [comment]
It should be highlighted to the user that by switching it becomes out-of-sync, ie, she does not update the repos README. Will do a PR

**Comment by imphil** [comment]
That's the very nature of a radio button that people have been used to for many years.

**Comment by wallento** [comment]
Sorry, but where exactly is the problem in being more verbose about the implications of pressing such a radio button? Don't know why this tone is necessary for such a simple issue.

**Comment by berndca** [comment]
I'm wondering why editing the README was introduced originally. I could imagine that the intent may have been to allow the user to do some minor touch up to make the document look presentable using the markdown js rendering. However over time is probably became clear that this is way beyond touch up.

There is of course the argument against having multiple (out of sync) documents covering the same subject.

I would recommend to use the [GitHub content API](https://developer.github.com/v3/repos/contents/#get-the-readme) to obtain the rendered html version of the README. This will return an HTML document how it was produced by GitHubs Markup engine.

Let me give you an example. Lets fetch the rendered README for kactus2/kactus2dev:
```
curl https://api.github.com/repos/kactus2/kactus2dev/readme -H "Accept: application/vnd.github.VERSION.html"  > README.html
```

Here is a compressed version of this file as reference. [README.html.zip](https://github.com/librecores/librecores-web/files/741943/README.html.zip)

From a user perspective I always appreciate when people are straight with me. That would mean in this case I would like to see a timestamp when the README was last updated and perhaps a link to where it came from.

**Comment by wallento** [comment]
Yes, the argument is that there is no need to have the information in two places.

The problem with using the Github API is that it is limited to Github only :) I consider using the GitHub API, Bitbucket API etc. as optimizations for projects hosted on one of the platforms. So, the most generic (and complicated) one is fetching from the Git repository. I think @eliaskousk already had a look at GitHub specific optimizations, right?

I agree on your last remark, can you please open a separate ticket for that.

**Comment by berndca** [comment]
Currently all projects registered on librecores.org are on GitHub. The only type of RCS supported by librecores is git. With git you can always put a fork of any repo anywhere on GitHub and have a cron job synchronize the GitHub shadow repo with the remote original. If that ever becomes necessary.

**Comment by wallento** [comment]
I generally agree and I would have started with the GitHub specific and then add generic.

Anyhow, there is a lot beyond the code we want to access and I think in the next call we should discuss how to best encapsulate this.

**Comment by wallento** [comment]
Finally, I will close this ticket. The PR #117 should cover the original issue.
