### ISSUE TITLE
Integrate an admin bundle like EasyAdmin

### ISSUE THREAD

**Issue by eliaskousk** [librecores/librecores-web#122]
I propose we install an admin bundle like [EasyAdmin Bundle](https://github.com/javiereguiluz/EasyAdminBundle) to easily view or edit our model data. This is very useful both for the LibreCores developers and non-developers to quickly make edits on e.g projects / orgs / users without resorting to manually entering queries on a regular SQL client. It will also allow us to visualize the current activity on production until we implement all the project / org / user listing / search etc features.

The other alternative would be to use [SonataAdmin Bundle](https://sonata-project.org/bundles/admin/3-x/doc/index.html) but the last time I used it on a project I was sick of the endless configuration work that was needed to have a result similar to the one we can have with less than 30 minute install and configuration of EasyAdmin bundle. Sonata is geared towards larger (enterprise) projects and can be configured in an endless way and thus I think it is not suitable for our needs on LibreCores.

Let me know if you agree and I can make a PR soon.

**Comment by imphil** [comment]
Elias, good idea, especially for development. For production, we need to make sure that (1) it's properly secured, and (2) that manual intervention cannot leave the DB in inconsistent state (i.e. dependencies which are not enforced by the entities or in the DB constraints, but in our business logic).

**Comment by eliaskousk** [comment]
Both points you raised are definitely important and I will keep them in mind while playing with it locally. When I feel they are both covered I will start a PR so that we can further discuss it. In the worst case that there are issues, especially with the consistency of the models, we can keep it for development only.

**Comment by imphil** [comment]
Yes, using it for development should be definitely  possible. (I also though about adding phpmyadmin or a similar mysql frontend to it, even though it's been a bit frowned upon) :)

**Comment by wallento** [comment]
Also note, that I recently played around with the Doctrine Extensions for Logging (Loggable). I think we should have this in place to record all changes. One nice feature of the loggable extension is that an entity can be versioned, i.e., the state can be restored at any time.

**Comment by eliaskousk** [comment]
Almost 4 months ago I promised this but still nothing. I know what you are thinking! But I really want us to have this, at least for development and Easy Admin is really easy to install - see what I did there? :p

**Comment by imphil** [comment]
merged and pushed.
