### ISSUE TITLE
DEV Environment error

### ISSUE THREAD

**Issue by berndca** [librecores/librecores-web#124]
I'm getting the following error message when I run the dev environment with the latest version of master:

```
 1/1 ClassNotFoundException in AppKernel.php line 30: Attempted to load class "ExerciseHTMLPurifierBundle" from namespace "Exercise\HTMLPurifierBundle".
Did you forget a "use" statement for another namespace?

    in AppKernel.php line 30
    at AppKernel->registerBundles() in bootstrap.php.cache line 2677
    at Kernel->initializeBundles() in bootstrap.php.cache line 2506
    at Kernel->boot() in bootstrap.php.cache line 2538
    at Kernel->handle(object(Request)) in app_dev.php line 28
```

**Comment by eliaskousk** [comment]
You seem to be missing the newly added html-purifier bundle. Ssh into your vm and do a composer install:
```bash
cd /var/www/lc/site
composer install
```

**Comment by imphil** [comment]
If you have any problem with the dev environment, please first do a vagrant destroy && vagrant up to rebuild the VM from scratch.

In this particular case, a vagrant provision would have also been sufficient, a composer install will solve this particular problem but then later on some dependencies will be missing.

**Comment by berndca** [comment]
Got it to work. Thanks!
