### ISSUE TITLE
Search is broken from the front page

### ISSUE THREAD

**Issue by olofk** [librecores/librecores-web#126]
Searching for a keyword on the main page only redirects to the search page, where a new search has to be performed

**Comment by imphil** [comment]
Hm, maybe in the restyling something went wrong. I'll get this fixed tonight.

**Comment by berndca** [comment]
Sorry, when changing from widgets to HTML the input name got lost. Just add  name="q" to the input tag in line 15 of /site/src/Librecores/SiteBundle/Resources/views/Default/home.html.twig.
