### ISSUE TITLE
Redirect to www.librecores.org

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#128]
GitHub OAuth login is only successful if we are calling from www.librecores.org, not librecores.org. Let's redirect everybody to www.librecores.org to have a single domain and less CORS and other issues.

**Comment by Agathver** [comment]
There's also a thing to consider: Since all those newer websites (twitter, github) have emrbaced the naked domains, without the 'www', it is increasingly common for people to actually skip typing the 'www'.

It would be wise to redirect people to whichever variant receives more hits.

**Comment by imphil** [comment]
In the end it doesn't matter, but since we already have components requiring the www version, let's pick this one. Fix is upcoming.
