### ISSUE TITLE
Sign in with GitHub returns "500 Internal Server Error"

### ISSUE THREAD

**Issue by adrianf0** [librecores/librecores-web#137]
Way to reproduce:
Register -> Sign in with GitHub -> Allow libre cores to access a github account information

After the last step, the libre cores webpage returns to:

> 
> We could not process your request
> The server returned "500 Internal Server Error". That's all we know.
> 
> Please open an issue at our Github repository and let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by imphil** [comment]
Hi Adrian, thanks for the report. It should be fixed now, the code change is already deployed. Please give it a try!

**Comment by adrianf0** [comment]
Hi Philipp, yes it works ! Thanks.
