### ISSUE TITLE
Extract repository metrics from git hosting provider APIs

### ISSUE THREAD

**Issue by agathver** [librecores/librecores-web#154]
Github and Gitlab provide extensive APIs to extract repository metadata, in addition to metrics such as issues and pull-requests that are helpful in determining the activity of a project.

The proposal is to augment the existing method of collecting repository metrics with git hosting provider specific APIs providing additional metrics.

- [x] GitHub ( #161  )
- [ ] GitLab

**Comment by imphil** [comment]
Let's close this for now as github is implemented and working. We can revisit gitlab support if there's a need for it from our users.
