### ISSUE TITLE
Add a linter based on projects code-style

### ISSUE THREAD

**Issue by agathver** [librecores/librecores-web#159]
To aid contributors and to lessen the burden while reviewing code, we should add a linter like [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer). It can be made as a part of the CI.

In the discussions at Gitter, we decided that we would follow [Symfony Coding Standards](https://symfony.com/doc/current/contributing/code/standards.html) with some modifications:
1. We will follow PSR-2 recommendations in regards to line length : 80 being the recommended length and 120 being a soft-limit.
2. We will not be strict about "yoda-conditions". Readability is the first priority.
3. We will not have strict restrictions for line-wrapping.
4. We will allow deviations from the standard for readability.

**Comment by imphil** [comment]
Thanks for the concise summary Amitosh.
