### ISSUE TITLE
5/5 stars shows 7 stars

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#177]
An image is better than thousand words.

![grafik](https://user-images.githubusercontent.com/1467123/30207190-f2823828-948e-11e7-94fe-087edf599690.png)

as seen on https://www.librecores.org/olofk/FuseSoC

**Comment by agathver** [comment]
Oh! This is embarrassing :/ Sending a fix soon

**Comment by imphil** [comment]
Actually that's a good thing, we should make sure that @olofk doesn't get too much credit for his work :)
