### ISSUE TITLE
Import from github only shows ~100 repos

### ISSUE THREAD

**Issue by olofk** [librecores/librecores-web#188]
Through my different organizations I track ~900 different repos. Only the 104 first of these (seemingly random selection) appear in the dropdown for importing projects from github. It was confirmed by @wallento that this problem starts to appear when the number of repos reach a certain threshold (~100?)

**Comment by wallento** [comment]
I just had a brief peek into the php library and 100 is the standard pagination size. So maybe @olofk miscounted and we just have to get all pages.

**Comment by wallento** [comment]
https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/ResultPager.php#L79

**Comment by olofk** [comment]
Ah, right. I was probably counting in base 9.6 instead of base 10. I do that sometimes

**Comment by agathver** [comment]
@wallento Doing that in the server-side will have a huge impact on the load time of the page.

**Comment by wallento** [comment]
@agathver yeah, it is also questionable how valuable a 760 entry dropdown menu is..

**Comment by wallento** [comment]
The best solution for now seems that we just display a free text input for users that have multiple pages.

**Comment by agathver** [comment]
@wallento Now that we have made the dropdown searchable, we can implement the code to add hundreds of options.

**Comment by wallento** [comment]
thats great! Isn't this problem solved then?

**Comment by agathver** [comment]
No, just client side part done, need to move the repo fetching code to the client side, if possible
