### ISSUE TITLE
Update service definitions to use new service IDs

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#195]
To make sure our code base stays up to date with best practices, we should switch our Symfony services to use the currently available features.

Follow these guides:
- https://knpuniversity.com/screencast/symfony-3.3/class-ids
- https://knpuniversity.com/screencast/symfony-3.3/private-services
- https://knpuniversity.com/screencast/symfony-3.3/auto-register-services
- https://knpuniversity.com/screencast/symfony-3.3/controllers-services

and subsequent chapters

**Comment by annika1** [comment]
Hey Philipp,
I would like to work on this issue. I guess the best idea is to go though the tutorial to symphony3.3 you have linked above?

**Comment by imphil** [comment]
Annika, great to see you join! You first need to set up a development environment, however. That's documented here: http://librecores-web.readthedocs.io/en/latest/devenv/quickstart.html  Let me know if you face any problems during this first step.

As next steps, as you said, follow the tutorial linked above (and just move on to the next chapters). It's probably best to start with the first (class-ids) topic/chapter and create a PR to get feedback early. Then you can move on to the next ones and update the PR iteratively.

**Comment by annika1** [comment]
I have already set up the development environment and can access the development page http://www.librecores.devel, therefore I will start now with the tutorial and the chapter to class-ids. I let you know, when problems come up.

**Comment by agathver** [comment]
Fixed in #312, #340
