### ISSUE TITLE
Provide ability to search the list of github repos to add

### ISSUE THREAD

**Issue by agathver** [librecores/librecores-web#196]
While adding a new project from GitHub, it is cumbersome to find a repository to add, if the user has considerable number of GitHub repositories (some of us have several hundred!).

I propose to use something like [this](https://silviomoreto.github.io/bootstrap-select/examples/#live-search).

**Comment by sandipbhuyan** [comment]
@agathver I am workin on this task. Up for finishing it very soon.

**Comment by sandipbhuyan** [comment]
@agathver Bootstrap select has its own css and js,  can I add it to the project?

**Comment by agathver** [comment]
@sandipbhuyan Absolutely
