### ISSUE TITLE
Add Chips4Makers blog to Planet LibreCores

### ISSUE THREAD

**Issue by Fatsie** [librecores/librecores-web#197]
I created a new blog for Chips4Makers: https://chips4makers.io/blog
I would like to ask to add it to the list of blog sources for Planet LibreCores
Looking at planet/config.ini I think this can be done by adding the following:

```

[https://chips4makers.io/blog/feeds/all.atom.xml]
Name = Chips4Makers
```

**Comment by imphil** [comment]
We're happy to add your blog to the planet. Could you open a pull request for this change? If you have trouble with that let me know, and we can handle it.

**Comment by Fatsie** [comment]
Done. I first did not go for a pull request as I don't proper setup for testing.
