### ISSUE TITLE
Error running Vagrant up

### ISSUE THREAD

**Issue by mayank1495** [librecores/librecores-web#207]
May be some changes in Vagrant broke the fetching of the box.
The error can be found here: [https://pastebin.com/8tnDc88n](https://pastebin.com/8tnDc88n)

**Comment by imphil** [comment]
I've updated the boostrap file to a newer version of Vagrant. Could you please pull the current master and run the bootstrap script again?

**Comment by mayank1495** [comment]
I did. After running ./bootstrap-dev.sh ,It downloads the required files and then there's a new error:

```
Preparing to unpack .../tmp/tmp.3uuNfyM1hy/vagrant.deb ...
Unpacking vagrant (1:2.0.2) over (1:1.9.1) ...
Setting up vagrant (1:2.0.2) ...
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  timed out (https://api.rubygems.org/specs.4.8.gz)

Source: https://rubygems.org/

```

**Comment by imphil** [comment]
According to the error message this looks like a temporary error in connectivity. Did you try again a bit later and is the mentioned url reachable for you?

**Comment by mayank1495** [comment]
Yes i tried multiple times but same error. From my browser I am able to access that url.

**Comment by imphil** [comment]
What you're seeing is/was either an infrastructure issue at the Vagrant side or a problem with your Internet connectivity. There are reports (e.g. https://github.com/hashicorp/vagrant/issues/8795) that this might be caused by broken IPv6 support, so trying to disable it might do the trick.

You can get more (possibly helpful) debugging output by running
```sh
vagrant plugin install vagrant-hostmanager --plugin-clean-sources --plugin-source https://rubygems.org --debug
```

Unfortunately, there's not much I can do from my side here as I cannot reproduce the issue.

**Comment by agathver** [comment]
@mayank1495 If you are on Jio, it's IP6 network to vagrant servers was not working since a while ago. I had to use a VPN or use another network.

**Comment by mayank1495** [comment]
Yes my bad. There was some network issue I guess. I am on to starting the development server by downloading the virtual box. I guess it will run fine after that.
Thank you.
