### ISSUE TITLE
Add a way to re-send confirmation link

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#212]
If users register on LibreCores they are sent an email with a link to confirm their email address. The UI should provide a way to re-send this confirmation link.

**Comment by sandipbhuyan** [comment]
i think I can resolve this issue. 
My approach is to make a separate page with separate route where the user can only enter his email to get its confirmation link again if the user haven't got it.

**Comment by aquibbaig** [comment]
@sandipbhuyan Is the issue resolved?
