### ISSUE TITLE
Footer broke design on project settings

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#223]
See this picture. Most likely some kind of clearfix missing.

![grafik](https://user-images.githubusercontent.com/1467123/37991820-7ac18d1a-320a-11e8-80ff-c61cb322bcad.png)

**Comment by sandipbhuyan** [comment]
This image is not showing the actual bug. I think we need to change the style of the footer
![screen shot 2018-04-01 at 1 43 19 pm](https://user-images.githubusercontent.com/18291428/38171217-ad3b8f92-35b2-11e8-8564-7f194c469761.png)

I am working on it and soon will raise a PR

**Comment by imphil** [comment]
PR #224 broke the page a bit differently. Most likely only one div is needed and the placement is wrong. Reverted in eee9cefc787802c067d10d1054c0c47b2b089810

![grafik](https://user-images.githubusercontent.com/1467123/38239635-96440194-372d-11e8-9c4e-dd6e2b4ed3b0.png)

**Comment by sandipbhuyan** [comment]
Actually, two `div`'s closing tags were missed one for `row` class and another for one column tag (col-sm-10). I may be closed those `div` at wrong place I am rectifying my error soon.
