### ISSUE TITLE
[GSoC] Classification System

### ISSUE THREAD

**Issue by sandipbhuyan** [librecores/librecores-web#230]
This issue is a meta-issue of #41 

The Classification system is a system in which the the IP Cores are being classified into categories. 
IP Cores will be classified in [Faceted classification](https://en.wikipedia.org/wiki/Faceted_classification) 

## **Rough Design Description:**

- IP Cores are classified in a [Faceted classification](https://en.wikipedia.org/wiki/Faceted_classification) 
- Every Project can be assigned to [1:n] categories and tags consist of two parts, the first is fixed architecture, type etc. and the second one is user supplied
- Categories are a hierarchy, which refines a topic

## **Benefits:**

- we have "moderated"/structured classifications
- the hierarchical structure allows users to select wider and more narrow categories based on the individual need

Example:
### Classification and Categorisation hierarchy: 

![screen shot 2018-05-03 at 1 51 12 pm](https://user-images.githubusercontent.com/18291428/39566407-160ae100-4ed9-11e8-8cd8-5d93495ee58e.png)

Here the categories are being divided into subcategories from which the classification and searching of details will be more easier. The hierarchical structure allows users to select wider and more narrow categories based on the individual need. Users can use this classification to search both for rough categories (e.g. all projects working on an FPGA by searching/filtering for "proven:fpga"), but also for very specific IP cores (e.g. "all out of order CPUs explicitly running on a 7 series xilinx device with "proven:fpga:xilinx:7series category:cpu")

The implementation of this structure can be divided into three sections
1. Extension of existing database schema
2. Providing a User Interface for adding categories
3. Searching for IP Cores from the classification hierarchy

The improvement of this issue will be tracked in #231

**Comment by imphil** [comment]
merged
