### ISSUE TITLE
[GSoC] Improve the LibreCores.org in terms of discoverability

### ISSUE THREAD

**Issue by sandipbhuyan** [librecores/librecores-web#231]
Here is the list of thing I would be working on during GSoC 2018. I
I will update this thing as I progress with the coding.

## First Evaluation

- [x] Representation of Classification System
- [x] Extending the database schema
- [x] Adding and updating categories in IP Cores
- [x] Unit Test and integration with UI

## Second Evaluation

- [x] Searching of IP Cores from Categories
- [x] Search engine page with an auto-complete feature on searching of IP Cores using Algolia.
- [x] Indexing and IP Cores
- [x] Unit test and integration with UI

## Third Evaluation

- [x] Displaying search result
- [x] Fixing issues related to Classification System and Search Engine Feature
- [x] Documentation of all implemented features

**Comment by agathver** [comment]
GSoC 2018 was a success!
