### ISSUE TITLE
Algolia instantsearch and autocomplete feature integration

### ISSUE THREAD

**Issue by sandipbhuyan** [librecores/librecores-web#245]
This Issue aims for the completion of algolia instantsearch and autocomplete feature. 
As described in issue #242 This issue will keep track of the bellow features

- [x] Autocomplete feature 
- [x] Insantsearch
- [x] Search Result

**Comment by imphil** [comment]
Merged in 550622e1363cdf6b2c6fa564023f8d8ef1799140
