### ISSUE TITLE
Search Through classifications

### ISSUE THREAD

**Issue by sandipbhuyan** [librecores/librecores-web#247]
This feature is to implement search functionality through classifications. The user will have the classification hierarchy and he can search through the projects related to the classifications. 

## Overview 
- [x] Classification hierarchy 
- [x] Searching through the classifications

I have done some work on this feature and I have opened this issue for the discussion process to make a better user interface. Until now the classification hierarchy that is going to display on the UI is like
![screen shot 2018-07-10 at 3 30 38 am](https://user-images.githubusercontent.com/18291428/42478251-aaa0e290-83f1-11e8-843d-c5e504d985c8.png)
 
And For searching through a specific classification I think I Prefer redirection method like [Pypi](https://pypi.org/search/?q=&o=) is currently doing.
@imphil  and @agathver I am open to taking suggestions to make it a better feature.

**Comment by imphil** [comment]
Should be there in 550622e1363cdf6b2c6fa564023f8d8ef1799140, bugs as they show up as new issue please.
