### ISSUE TITLE
Add cache busting for CSS assets

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#260]
In staging I noticed that the app.css is not using cache-busting, causing changes to go unnoticed by browsers. Use https://symfony.com/doc/current/reference/configuration/framework.html#version and version_format to fix that before going to production.

**Comment by aquibbaig** [comment]
@imphil can I work on this issue?

**Comment by aquibbaig** [comment]
We should switch to webpack, instead of moving further with Assetic. Encore provides this out of the box.

**Comment by imphil** [comment]
Is webpack the current "de facto" standard, or has it been superseded by another thing already? Maybe @agathver knows more?

**Comment by aquibbaig** [comment]
@imphil I had a talk with @agathver. He only suggested that we should migrate to webpack encore

**Comment by aquibbaig** [comment]
@imphil @agathver Will I consider a green light for `webpack-encore`

**Comment by agathver** [comment]
Sure go ahead!

**Comment by aquibbaig** [comment]
I think we need yarn in our vm to install webpack in the first place. Can someone help me out with ansible?
`https://symfony.com/doc/current/frontend/encore/installation.html`

**Comment by imphil** [comment]
@aquibbaig please note that this bug is about cache busting. Please keep the discussion about assetic and its alternatives in #292 .

**Comment by imphil** [comment]
fixed by switching to webpack in 2dfec83
