### ISSUE TITLE
Classification validation sometimes fails

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#263]
STR:
- Go to the settings page of any project
- Add the classification "Proven on::FPGA::Altera/Intel"
- Click on "Add classification"
- Click on "Update Project"

Result:
Error message " Invalid classifications - Proven on::FPGA::Altera/Intel "

Expected Result:
classification is added

@sandipbhuyan you mentioned this or a similar bug in the last call, but I didn't find an open issue.

**Comment by sandipbhuyan** [comment]
I am currently working on this bug And By tomorrow I will be submitting one PR on this.

**Comment by sandipbhuyan** [comment]
I have made some mistakes in my javascript that is why the code is being broken. Actually Prove on::FPGA has no child node.
