### ISSUE TITLE
Git commit SHA should not be considered unique in Commit entity

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#267]
Currently I get on staging failures to crawl a project which has been added twice to LibreCores:

~~~
11:53:09 INFO      [app] Processing of repository resulted in an Doctrine\DBAL\Exception\UniqueConstraintViolationException with message An exception occurred while executing 'INSERT INTO Commit (commitId, dateCommitted, filesModified, linesAdded, linesRemoved, sourceRepo_id, contributor_id) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["734246889653fc64464dbfafb3498f10b3dc6ce4", "2013-07-17 22:05:24", "354", "966547", 0, 7, 47]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '734246889653fc64464dbfafb3498f10b3dc6ce4' for key 'UNIQ_49782B9BEDC2C24D'
~~~

The underlying problem is that we assume commitId to be unique and use it as key. That's wrong for two reasons:
- Git SHA commit IDs are not guaranteed to be globally unique.
- Adding the same source repo to LibreCores multiple times is possible currently. There's also no clean way of preventing that. 

So we should fix the constraint and make a combination of SourceRepo + Commit the index.

**Comment by imphil** [comment]
@agathver do you think you can find time to fix that?

**Comment by agathver** [comment]
Just removing the unique constraint should work. 

> @agathver do you think you can find time to fix that?

@imphil I'm travelling from tomorrow. Will take a week before I can take a look at this issue.
