### ISSUE TITLE
Multiple classifications displayed comma-separated in search results

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#268]
See https://www.stage.librecores.org/search?query=Target::FPGA::Xilinx::7%20series&type=projects

![grafik](https://user-images.githubusercontent.com/1467123/43676513-42963b12-97f3-11e8-8dc3-c81fd3e3483e.png)

I have not seen this before the latest composer update, which also included a minor update on Algolia. Maybe it's caused by that, maybe I just didn't see it before?

**Comment by sandipbhuyan** [comment]
I think there will be some problem while pushing the data into algolia
