### ISSUE TITLE
Processing hangs when two projects have the same git URL

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#279]
Processing never returns, no error message is logged on server side.

**Comment by agathver** [comment]
What should be the correct behaviour? Should we allow the users to create duplicate project listings or disallow duplicated repository URLs?

**Comment by agathver** [comment]
I added two projects with the same repository URL, but different name. The crawlers successfully processed the projects and data was visible in both the projects

**Comment by imphil** [comment]
> What should be the correct behaviour? Should we allow the  users to create duplicate project listings or disallow duplicated  repository URLs?

Disallowing two projects with the same repository URL is a sane option.

**Comment by olofk** [comment]
I don't agree. Some people store collections of IP in a single repo. But it can make sense to list these as separate projects on LC. Of course, if this complicates the implementation I'm fine to disallow this for now and revisit later

**Comment by imphil** [comment]
Wasn't reproducible any more.
