### ISSUE TITLE
Allow creation of new project

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#28]

**Comment by imphil** [comment]
local vagrant: http://librecores.devel/projects/new

feature set for Milestone 1
* create projects in personal namespace (no organizations, etc.) only
* create projects from git repositories only
* import README and LICENSE from git repository

**Comment by olofk** [comment]
Just imported a project and everything seems to work fine.
It picked up both my README.md and LICENSE files.
Adding data to the project fields updates the data sheet
