### ISSUE TITLE
Switch away from assetic

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#292]
The symfony assetic bundle is being deprecated, the suggested replacement is Webpack Encore (https://symfony.com/doc/current/frontend.html). We should consider switching as well to give us (in addition to a maintained library) a more "standard" frontend experience and enable the use of frameworks like vue.js for some frontend pieces.

**Comment by aquibbaig** [comment]
If we implement this, it will solve #260 as well.

**Comment by aquibbaig** [comment]
#353 currently is in progress to migrate from Assetic to webpack. 
There are a few things we need to tackle for configuring page-specific CSS files. Each file that webpack builds is an independent file of its own with all its dependencies intact. We have some twig files in which we need to pass twig filters to the jquery functions. 

**For example:**
> $('#{{ form.descriptionText.vars.id }}').trumbowyg(trumbowyg_config);
  $('#{{ form.licenseText.vars.id }}').trumbowyg(trumbowyg_config);

The above code here is from `LibrecoresProjectRepoBundle:Project:settings.html.twig` which uses a twig parameter `{{ form.descriptionText.vars.id }}`. For bundling it with webpack, this parameter needs to be accessed inside a single javascript file. I believe refactoring all the javascript in this page, i.e. `LibrecoresProjectRepoBundle:Project:settings.html.twig` to a single js file can be an example to refactor other similar situations. Can anyone help me out in this? @agathver @imphil @sandipbhuyan

**Comment by agathver** [comment]
@imphil Do we even use trumbowyg anywhere?

**Comment by imphil** [comment]
> page-specific CSS files.

did you mean JS files?

**Comment by imphil** [comment]
> @imphil Do we even use trumbowyg anywhere?

yes, in the project settings page for the LICENSE and README text boxes

**Comment by aquibbaig** [comment]
@agathver in the LICENSE and DESCRIPTION fields

**Comment by agathver** [comment]
@aquibbaig Here's a suggested approach:
- Assign a class (let's say: `.trumbowyg-textbox`) to each of the text areas that use trumbowyg.
- Use a jQuery selector to find any `.trumbowyg-textbox` in a page.
- Use [dynamic imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_imports) to load trumbowyg and initialize them.

```js
let textareas = $('.trumbowyg-textbox);
if(textareas.length) {
    import('/modules/my-module.js')
        .then(() => {
            textareas.trumbowyg({
                // ...
            });
    });
}
```

**Comment by aquibbaig** [comment]
@agathver Did a few `console.log()` to figure out id's and replaced the earlier code. Any workaround for accessing the `classificationHierarchy` variable passed from the controller in an external js file?
