### ISSUE TITLE
Releases should sort by date, not by version number

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#294]
In the mor1kx project the 5.0-rc1 release is considered "newer" than the "5.0" release.

https://www.librecores.org/openrisc/mor1kx

![image](https://user-images.githubusercontent.com/1467123/51090969-c7ae0e80-177b-11e9-9600-789fb570ca75.png)

**Comment by olofk** [comment]
Small note, it's not rc, but revision (some background here https://devmanual.gentoo.org/general-concepts/ebuild-revisions/index.html). Ideally, the projects themselves should not be tagged with -r labels. This is a packaging detail

**Comment by wallento** [comment]
So, its like the .post releases in python, right? The ordering is correct in this case then.

**Comment by olofk** [comment]
Yes, it's correct, but reading again I see what @imphil means. If it _had_ been rc, then it would be wrong order. Sorting by date makes more sense

**Comment by imphil** [comment]
thinking about this again it seems that the order is actually right, otherwise the fpu one wouldn't be at the bottom. Closing for now.

**Comment by wallento** [comment]
Anyhow, we should change it to using a patch version number instead for mor1kx..

**Comment by agathver** [comment]
@imphil We already sort it by descending order of date: See https://github.com/librecores/librecores-web/blob/master/site/src/Librecores/ProjectRepoBundle/RepoCrawler/GitRepoCrawler.php#L408
