### ISSUE TITLE
Fix ansible deprecations

### ISSUE THREAD

**Issue by agathver** [librecores/librecores-web#297]
Ansible has changed the behavior of `apt` and now accepts multiple packages in a single command. The old way of running apt with `with_items` has been deprecated and is scheduled to be removed soon.

We have around 5-6 usages of apt with `with_items` we need to migrate them to the new syntax.

**Comment by imphil** [comment]
Note that we have still users of Ubuntu 16.04, which comes with Ansible 2.0.

**Comment by agathver** [comment]
Ansible team always recommends to use the official ansible PPA. It has more features and is kept updated. We can note that in our readme.
