### ISSUE TITLE
Fix the size of Librecores CI.Project overview 

### ISSUE THREAD

**Issue by Nancy-Chauhan** [librecores/librecores-web#303]
User Interface of [Librecores CI ](https://www.librecores.org/static/librecores-ci ) can be Improved by adjusting the size of Presentation so that it is easily readable .

![screenshot from 2019-02-21 12-58-11](https://user-images.githubusercontent.com/37153406/53151139-624e0880-35d8-11e9-94dc-cf85ee9b5d00.png)

**Comment by aquibbaig** [comment]
Hello. I can work on this!

**Comment by Nancy-Chauhan** [comment]
Fixed by #304
