### ISSUE TITLE
Re-request GitHub credentials if we get a "bad credentials" exception

### ISSUE THREAD

**Issue by adrianf0** [librecores/librecores-web#305]
I get a _500 Internal Server Error_ when I try to add a new project by clicking my username in the right top corner.

**Comment by imphil** [comment]
Sentry issue: [LIBRECORES-WEB-X](https://sentry.io/organizations/librecores/issues/928613875/?project=221297&referrer=github_plugin)

**Comment by imphil** [comment]
Looks like the GitHub API credentials you've cached are not up-to-date. How did you log into LibreCores? Through GitHub, or did you enter a username and password?

Backtrace:

```
Github\Exception\RuntimeException: Bad credentials
#14 vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php(87): Github\HttpClient\Plugin\{closure}
#13 vendor/php-http/httplug/src/Promise/HttpFulfilledPromise.php(34): then
#12 vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php(88): handleRequest
#11 vendor/php-http/client-common/src/PluginClient.php(160): Http\Client\Common\{closure}
#10 vendor/php-http/client-common/src/PluginClient.php(174): Http\Client\Common\{closure}
#9 vendor/php-http/client-common/src/PluginClient.php(87): sendRequest
#8 vendor/php-http/client-common/src/HttpMethodsClient.php(203): sendRequest
#7 vendor/php-http/client-common/src/HttpMethodsClient.php(192): send
#6 vendor/php-http/client-common/src/HttpMethodsClient.php(61): get
#5 src/Librecores/ProjectRepoBundle/Controller/ProjectController.php(467): getGithubRepos
#4 src/Librecores/ProjectRepoBundle/Controller/ProjectController.php(46): newAction
#3 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): handleRaw
#2 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): handle
#1 vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): handle
#0 web/app.php(27): null
```

**Comment by adrianf0** [comment]
I entered a username and password.

**Comment by imphil** [comment]
Can you try logging in with GitHub and see if that fixes the issue for you? 

As a longer-term fix, we probably need to re-request GitHub credentials if we get that exception.

**Comment by adrianf0** [comment]
I confirm that by logging through GitHub I can enter 'New project' page (no _500 Internal Server Error message_).

**Comment by imphil** [comment]
@adrianf0 thanks for confirming that. I've changed the bug title to better reflect what needs to be done to prevent such a scenario in the future.

**Comment by agathver** [comment]
Summerizing discussion: 

GitHub access tokens do not expire. when there is a 403 from GitHub API, the user has revoked the connection from LibreCores due to some reason. 

Currently we refresh the access token on each GitHub login. 

On a crawl failure we will mark the token as expired and display a notice to the user to reconnect their github account. We may even send an email mentioning this.
