### ISSUE TITLE
Problem with avatar

### ISSUE THREAD

**Issue by adrianf0** [librecores/librecores-web#307]
In the project which I have added recently ([link](https://www.librecores.org/adrianf0/hdlregs)), my avatar (I presume it should be downloaded from GitHub) in the right Data Sheet tab under contributors is not displayed.
It could be related to the fact, that commits have been done with nondefault e-mail address.

**Comment by agathver** [comment]
>  It could be related to the fact, that commits have been done with nondefault e-mail address.

Yes. We check using for the email in _Gravataar_ and not in Github, yet.

To map multiple emails, you can use a mailmap: https://developer.atlassian.com/blog/2017/06/aliasing-authors-in-git/

**Comment by adrianf0** [comment]
I see. Simply GitHub avatars are not supported yet. Thanks for the update.

**Comment by imphil** [comment]
@adrianf0 Is Gravatar working for you and we can close this issue?

**Comment by adrianf0** [comment]
At the moment I not thinking about creating an account on Gravatar, so I think the issue can be closed.
