### ISSUE TITLE
Merge bundles together into a single AppBundle

### ISSUE THREAD

**Issue by agathver** [librecores/librecores-web#322]
From Symfony documentation

> ...it was recommended to organize your own application code using bundles. This is no longer recommended and bundles should only be used to share code and features between multiple applications.

We have very little code to be put in their own bundles, and bundle splitting just forces us to look up different files for configuration. Merging them into a single bundle will bring all configuration to a single place.

Effect on code quality will not be much IMO, the existing controller and services continue to exist as they were and no additional coupling would be introduced.

**Comment by imphil** [comment]
Let's do it!
