### ISSUE TITLE
Support SSL

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#34]
Include automated cert installation from letsencrypt in ansible

**Comment by wallento** [comment]
I have sent you the certificate as PM.

**Comment by imphil** [comment]
? The cert will be auto-generated (and renewed) during deployment, so should be only changes in Ansible.

**Comment by oleg-nenashev** [comment]
@imphil I doubt you will be able to generate a verified certificate in such way. Browsers still do not like letsencrypt IIRC.

**Comment by wallento** [comment]
you mean for the development environments, imphil, right? For the production and stage we have this startssl cert I sent you

**Comment by imphil** [comment]
all (TM) browsers accept letsencrypt, as it's cross-signed by a built-in CA. so no need to use the arcane startssl web interface any more :)

**Comment by imphil** [comment]
fixed in dc81022e97d7df4b3770a73657dfce5fe44b6085, deployed to staging already.
https://stage.librecores.org

We're using an intermediate security level to support older browsers (Firefox 1, Chrome 1, IE 7, Opera 5, Safari 1, Windows XP IE8, Android 2.3, Java 7) as they can most likely be found in industry. 

SSL test results: https://www.ssllabs.com/ssltest/analyze.html?d=stage.librecores.org&latest
