### ISSUE TITLE
Ansible task fails at "Install RabbitMQ"

### ISSUE THREAD

**Issue by aquibbaig** [librecores/librecores-web#359]
> fatal: [librecores]: FAILED! => {"cache_update_time": 1558203602, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'rabbitmq-server'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n rabbitmq-server : Depends: erlang-base (< 1:22) but 1:22.0-1 is to be installed or\n                            erlang-base-hipe (< 1:22) or\n                            esl-erlang (< 1:22)\n                   Depends: erlang-crypto (< 1:22) or\n                            esl-erlang (< 1:22)\n                   Depends: erlang-eldap (< 1:22) but 1:22.0-1 is to be installed or\n                            esl-erlang (< 1:22)\n                   Depends: erlang-inets (< 1:22) or\n                            esl-erlang (< 1:22)\n                   Depends: erlang-mnesia (< 1:22) or\n                            esl-erlang (< 1:22)\n                   Depends: erlang-os-mon (< 1:22) or\n                            esl-erlang (< 1:22)\n                   Depends: erlang-parsetools (< 1:22) or\n                            esl-erlang (< 1:22)\n                   Depends: erlang-public-key (< 1:22) or\n                            esl-erlang (< 1:22)\n                   Depends: erlang-runtime-tools (< 1:22) or\n                            esl-erlang (< 1:22)\n                   Depends: erlang-ssl (< 1:22) or\n                            esl-erlang (< 1:22)\n                   Depends: erlang-syntax-tools (< 1:22) or\n                            esl-erlang (< 1:22)\n                   Depends: erlang-tools (< 1:22) or\n                            esl-erlang (< 1:22)\n                   Depends: erlang-xmerl (< 1:22) or\n                            esl-erlang (< 1:22)\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " rabbitmq-server : Depends: erlang-base (< 1:22) but 1:22.0-1 is to be installed or", "                            erlang-base-hipe (< 1:22) or", "                            esl-erlang (< 1:22)", "                   Depends: erlang-crypto (< 1:22) or", "                            esl-erlang (< 1:22)", "                   Depends: erlang-eldap (< 1:22) but 1:22.0-1 is to be installed or", "                            esl-erlang (< 1:22)", "                   Depends: erlang-inets (< 1:22) or", "                            esl-erlang (< 1:22)", "                   Depends: erlang-mnesia (< 1:22) or", "                            esl-erlang (< 1:22)", "                   Depends: erlang-os-mon (< 1:22) or", "                            esl-erlang (< 1:22)", "                   Depends: erlang-parsetools (< 1:22) or", "                            esl-erlang (< 1:22)", "                   Depends: erlang-public-key (< 1:22) or", "                            esl-erlang (< 1:22)", "                   Depends: erlang-runtime-tools (< 1:22) or", "                            esl-erlang (< 1:22)", "                   Depends: erlang-ssl (< 1:22) or", "                            esl-erlang (< 1:22)", "                   Depends: erlang-syntax-tools (< 1:22) or", "                            esl-erlang (< 1:22)", "                   Depends: erlang-tools (< 1:22) or", "                            esl-erlang (< 1:22)", "                   Depends: erlang-xmerl (< 1:22) or", "                            esl-erlang (< 1:22)"]}

This is what I get as an error message. I tried to check that up. This is most likely a problem with the Erlang dependency.

**Comment by aquibbaig** [comment]
@imphil Again encountered an issue regarding rabbitmq, which is:
> fatal: [librecores]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:The repository 'https://dl.bintray.com/rabbitmq-erlang/debian xenial Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., E:Failed to fetch https://dl.bintray.com/rabbitmq-erlang/debian/dists/xenial/erlang-21.x/binary-amd64/Packages  404  Not Found, E:Some index files failed to download. They have been ignored, or old ones used instead."}

**Comment by imphil** [comment]
Please open a new issue when you encounter different issues.

It looks like this is a temporary issue, please try again in a couple of minutes/hours.

**Comment by aquibbaig** [comment]
> failed: [librecores] (item=deb https://dl.bintray.com/rabbitmq-erlang/debian xenial erlang-21.x) => {"changed": false, "item": "deb https://dl.bintray.com/rabbitmq-erlang/debian xenial erlang-21.x", "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1558481332.67-192543234908116/AnsiballZ_apt_repository.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1558481332.67-192543234908116/AnsiballZ_apt_repository.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1558481332.67-192543234908116/AnsiballZ_apt_repository.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_apt_repository_payload_LBpxdT/__main__.py\", line 549, in <module>\r\n  File \"/tmp/ansible_apt_repository_payload_LBpxdT/__main__.py\", line 541, in main\r\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 503, in update\r\n    raise FetchFailedException(e)\r\napt.cache.FetchFailedException: W:The repository 'https://dl.bintray.com/rabbitmq-erlang/debian xenial Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., E:Failed to fetch https://dl.bintray.com/rabbitmq-erlang/debian/dists/xenial/erlang-21.x/binary-amd64/Packages  404  Not Found, E:Some index files failed to download. They have been ignored, or old ones used instead.\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
failed: [librecores] (item=deb https://dl.bintray.com/rabbitmq/debian xenial main) => {"changed": false, "item": "deb https://dl.bintray.com/rabbitmq/debian xenial main", "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1558481353.47-278740387247745/AnsiballZ_apt_repository.py\", line 113, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1558481353.47-278740387247745/AnsiballZ_apt_repository.py\", line 105, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1558481353.47-278740387247745/AnsiballZ_apt_repository.py\", line 48, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/tmp/ansible_apt_repository_payload_NHXvaJ/__main__.py\", line 549, in <module>\r\n  File \"/tmp/ansible_apt_repository_payload_NHXvaJ/__main__.py\", line 541, in main\r\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 503, in update\r\n    raise FetchFailedException(e)\r\napt.cache.FetchFailedException: W:The repository 'https://dl.bintray.com/rabbitmq-erlang/debian xenial Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., E:Failed to fetch https://dl.bintray.com/rabbitmq-erlang/debian/dists/xenial/erlang-21.x/binary-amd64/Packages  404  Not Found, E:Some index files failed to download. They have been ignored, or old ones used instead.\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

I try to destroy and rerun to see this at **Add RabbitMQ and Erlang repositories (maintained by RabbitMQ)]**

**Comment by aquibbaig** [comment]
Updates:
`Reverting it to the previous file version works`
