### ISSUE TITLE
"Insert Database fixtures" fails

### ISSUE THREAD

**Issue by aquibbaig** [librecores/librecores-web#361]
>name: Insert database fixtures
  become: true
  become_user: "{{ web_user }}"
  command: php bin/console doctrine:fixtures:load -n
  environment: "{{ symfony_config }}"
  args:
    chdir: /var/www/lc/site

**Doesn't work**

Expected directory of Datafixtures: `/var/www/lc/site/app/DataFixtures/ORM/`
Provided: `/var/www/lc/site/src/DataFixtures/ORM`

command: `php bin/console datafixtures:load` throws error in ansible
Does this show for any of you?

**Comment by imphil** [comment]
@agathver do you have a fix for this? It's critical as it blocks all other testing.

**Comment by agathver** [comment]
Should have fixed in #364, if not let me have a look now

**Comment by imphil** [comment]
No, it's not. Using the branch from #364 and doing a vagrant destroy; vagrant up shows a fixture problem and aborts.
