### ISSUE TITLE
[GSoC 2019] Design of the Notification System

### ISSUE THREAD

**Issue by aquibbaig** [librecores/librecores-web#363]
In Reference to #143 

The notification system will be used to notify users of notable events generated on the Librecores Website. This is the first project goal for GSoC 2019.

### Design
The primary goal of this issue is to inform the Users about events that happen on the website. Also, the community may want to notify their audience with relevant information. This can be accomplished via emails or text messages to notify users of various events and extract useful information. As a user, I can click on the bell icon on the top-right of the navbar and view the list of notifications that I have received and if I’m not logged into the website currently, can receive important notifications as an email from the community. The notifications will contain vital information about the event that he/she was associated with.

### For Example:
**Notify users for the status of RepoCrawler crawling for project metrics and relevant information on GitHub**
![notification_design_copy](https://user-images.githubusercontent.com/26324376/58614982-873cd080-82d7-11e9-9a62-6f519096ece6.jpg)

### Routing Options
The notifications would have a type, either **email** or **web** to distinguish if we need to send an email or a web notification. 

### UI/UX
- The User will be able to see a bell icon on the top right-hand corner of the webpage that would contain the list of notifications for him.
- Clicking on the bell icon views his/her list of notifications
- Important Notifications can be sent from the community directly through the email to the user Inbox

### List of Events to support
- Advertisements from the community
- Creation of a project
- RepoCrawler action(succeeded/failed)
- Classifications updated for a project

### How do we want it to look like
<img src="http://i.imgur.com/07OcF6c.gif">

[*Docs link for the proposal*](https://docs.google.com/document/d/1RHJmSgOreDmp-kyAUarVN0VT6rKqNjqVRzobd0bXR-U/edit?ouid=101184194438781061141&usp=docs_home&ths=true )

**Comment by imphil** [comment]
A couple comments:

- This is *only* about the design. Remove the implementation part.
- Be very specific. 
  - "Notifications are coming from events such as signing into Librecores website, repocrawler fails, etc." What events *exactly*? List all events you want to support right now.
  - "Notifications are supposed to have fields that concern the user and event such as a description of the event, who sent it, etc." What fields *exactly*? List every field that is associated with a message.
- The design is only from a user's perspective, not implementation details. For example: "We can associate controller actions with creation of notification entities and store them in database" How is that user-visible?


How about you draw a data flow diagram (e.g. in UML-style) showing where notifications are coming from, what routing options exist (you skipped this part mostly so far), and how they can be output.

**Comment by aquibbaig** [comment]
@imphil Updated the proposal!
