### ISSUE TITLE
[GSoC 2019] Decide a routing mechanism for notifications

### ISSUE THREAD

**Issue by aquibbaig** [librecores/librecores-web#379]
Based on the recent discussion, we need to set up how to parse a notification **type** and then route it to its specific path(If its email type, send a mail or if it's web type, store in the db and fetch to the frontend). @imphil suggested to implement it using a cronjob or rabbitmq.  

- I guess we won't have that much traffic  and sending a notification won't take that many of processing overhead, so what about this? 
```
1. $notif = $manager->createNotification('Notification subject', 'Some random text', 'https://google.fr/', 'web');  
2. sendNotification($notif);
```
This means after a notification is created -> send it accordingly in the next step. If it's web type store in the database. If it's email type, don't store and just send a mail. 
@agathver @imphil @sandipbhuyan  Let me know your thoughts

**Comment by imphil** [comment]
Questions:
- Where/how do you store the routing configuration? This can be global (all messages of type x to go email), and user-specific (user disabled getting emails about type y).
- You cannot synchronously send emails, you need to queue the email send requests somehow. You didn't really answer that question in issue #363 and that's "haunting" you now.

Look at the picture below for an architecture I'd use. It doesn't answer the routing part in code yet, it only shows you where to hook it up (in the consumer). 

![image](https://user-images.githubusercontent.com/1467123/59163316-43c43c80-8af7-11e9-9cca-d53e5e747f10.png)

You can have a look at the existing crawler code to see RabbitMQ and consumer/producers in action. It makes sense to just re-use this infrastructure and do the notification system in a similar way.


Use this proposed architecture as a starting point to further refine it. Make use of drawing such as this one to convey what you exactly mean, and be specific.
