### ISSUE TITLE
Console command to create test Notifications

### ISSUE THREAD

**Issue by aquibbaig** [librecores/librecores-web#388]
so, in the dev environment, we need a cli command to generate web notifications so that we can test them out.

# Issues
- How to handle Recipient information in the Notification data class: Until we have a recipient which is an instance of NotifiableEntity we cannot persist it as a Web Notification

**Comment by aquibbaig** [comment]
Fix: 
UserManager can help us get recipients for Notifications. I have assigned all users as the recipient of the notification one creates using this command, for now

**Comment by imphil** [comment]
Fixed in PR #389
