### ISSUE TITLE
Send notification on join organization request

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#411]
We need to send a notification when a "join organization" request is issued. This notification should go out to all current org members.

**Comment by aquibbaig** [comment]
So, to allow sending notification to multiple users, a small tweak to add recipients to arrayList will be done. So since I have worked on the notification system, would you mind if I take this issue up?

**Comment by imphil** [comment]
Just send the notification one by one, no need to change the notification system itself.

**Comment by aquibbaig** [comment]
Was testing this out. I probably have sent a request already, please don't mind.
