### ISSUE TITLE
Notification Settings: Side navigation bar not selected

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#413]
STR:
- Click on the "Notification Settings" in the user settings

Expected result:
- Green bar left to the "Notification Settings" entry is shown, marking it as active.
![image](https://user-images.githubusercontent.com/1467123/63253265-cb55c680-c271-11e9-9f6f-4acb426cb8a8.png)
Compare this with the other subpages, e.g. "Change Password"

Actual result:
- The green bar isn't shown.

@aquibbaig can you have a look at that?

**Comment by aquibbaig** [comment]
Sure. Let me have a look at it.

**Comment by aquibbaig** [comment]
Fixed in #414
