### ISSUE TITLE
Create LibreCores organization on DockerHub

### ISSUE THREAD

**Issue by oleg-nenashev** [librecores/librecores-web#42]
As a follow-up to discussion with @wallento, we wiould like to setup a Docker Hub organization, which would store Docker images we use for automation of Librecores and EDA tools we use.

TODO:
- [x] Setup organization
- [ ] Move some Docker images we use to this organization
- [x] Add @wallento and maybe others as owners
- [ ] Add documentation to the internal Wiki

**Comment by oleg-nenashev** [comment]
Organization is here: https://hub.docker.com/u/librecores

**Comment by oleg-nenashev** [comment]
@wallento Could you let me know your DockerHub ID?

**Comment by wallento** [comment]
Thanks!

My DockerHub ID is wallento

**Comment by oleg-nenashev** [comment]
@wallento added you. @olofk @imphil please ping me if you need an access as well

**Comment by imphil** [comment]
oleg, please add me as well. "imphil" is also used by me on docker hub

**Comment by oleg-nenashev** [comment]
done

**Comment by oleg-nenashev** [comment]
3 admins are enough for the kick-off. Marking it as "done"
