### ISSUE TITLE
ParentUser for a project is NULL in the Consumer

### ISSUE THREAD

**Issue by aquibbaig** [librecores/librecores-web#420]
Need to fix this before moving on to #419 

## Code1 (File to look: ProjectController.php)
```
Create a project -> setParentUser($this->getUser())
```
## Result on var_dump($project)
![Photo from Aquib Baig](https://user-images.githubusercontent.com/26324376/63652864-e39e7780-c782-11e9-877c-07dd3bc98184.jpg)

## Code 2 (File to look: QueueDispatcherService.php)
```
$this->producer->publish(serialize($project->getId()));
```

### Code 3 (File to look: AbstractProjectUpdateConsumer.php)
```
$projectId = (int) unserialize($msg->body);
$project = $this->repository->find($projectId);
```

### Result on var_dump($project)
![Photo from Aquib Baig (1)](https://user-images.githubusercontent.com/26324376/63652894-69babe00-c783-11e9-9d28-cd91089ec1e3.jpg)

--- 
I wanted to setRecipient() for a notification inside the UpdateProject consumer to show crawling failures/success but `getParentUser` returns NULL, which is evident from the second image

**Comment by imphil** [comment]
In the second case, the project is owned by an organization, not a user. You need to send a notification to all organization owners in this case.

**Comment by aquibbaig** [comment]
@imphil Yes!
