### ISSUE TITLE
Github update not getting reflected

### ISSUE THREAD

**Issue by findnabeel** [librecores/librecores-web#426]
I have uploaded the project (https://www.librecores.org/mtn2/cophee) by linking the github page. But it looks like any further change in the github Readme is not getting reflected in the librecore site.
As of now, I am relying on the workaround I got from the "https://gitter.im/librecores/Lobby", which is by appending a "/update" to the end of the project URL.

**Comment by alexforencich** [comment]
I have a similar issue with https://www.librecores.org/alexforencich/corundum .  I added this with https://github.com/ucsdsysnet/corundum as the repo first, but after the initial scrape it never updated.  So I changed it to point to my fork at https://github.com/alexforencich/corundum, but it never updated.  Adding /update to the end of the URL did refresh the readme, but the metadata has not updated.  Is there a way to kick-start things?  If not, is there a way to delete the project on librecores, purge everything, and add it again?

**Comment by agathver** [comment]
@alexforencich Just queued an update manually, what changes are you expecting though?

**Comment by alexforencich** [comment]
All of the metadata/project metrics on the librecores page are 7 months out of date, it seems.  For example, the librecores page says the last update was 7 months ago.  However, the last update was 3 days ago.  Similarly, it says there are 1043 commits, but the real number is 1327.  Everything on the "project metrics" tab is similarly out of date.  So it updated the readme, but nothing else.

**Comment by imphil** [comment]
Thanks for your issue. I think I know what's going on, I'll have a look tonight.

**Comment by imphil** [comment]
I made a first step towards getting the metadata updates back in order in https://github.com/librecores/librecores-web/commit/d52f89aa866bafe7e72fee9ed68c90e3500e692c, but looks like we're not quite there yet. I'll continue looking.

**Comment by imphil** [comment]
Thanks @alexforencich for this bug report. I've now tracked down the issue and updated refreshed the data, it looks good now from all I can tell (https://www.librecores.org/alexforencich/corundum). Please have a look and let me know if anything is still not quite right!

@findnabeel also thank you for your bug report. I'm sorry it took so long to get this resolved. Also for you: please let me know if there's something wrong still!
