### ISSUE TITLE
Changing repo link does not update project info

### ISSUE THREAD

**Issue by olofk** [librecores/librecores-web#429]
I was adding a new project but chose the wrong repo. I changed the links and tried to force an update but the info from the initial report is still there.

https://www.librecores.org/olofk/led-to-believe is the project

**Comment by Kajol-Kumari** [comment]
you can try any of the two options mentioned here at https://github.community/t5/How-to-use-Git-and-GitHub/Project-attached-to-the-wrong-github-repo/td-p/1182.

**Comment by imphil** [comment]
Should be all good now @olofk?

**Comment by olofk** [comment]
Never looked better!
