### ISSUE TITLE
Infra: Create Gravatar account for librecores@fossi-foundation.org

### ISSUE THREAD

**Issue by oleg-nenashev** [librecores/librecores-web#43]
Several services like DockerHub use Gravatar to display logos.
It would be great to setup Gravatar account for librecores@fossi-foundation.org, so we will be able to retrieve logo from it.

**Comment by oleg-nenashev** [comment]
Nice2have for #42

**Comment by oleg-nenashev** [comment]
CC @wallento

**Comment by wallento** [comment]
Done, uploaded the librecores logo there
