### ISSUE TITLE
Unable to setup the development setup

### ISSUE THREAD

**Issue by Kajol-Kumari** [librecores/librecores-web#433]
While setting up the development setup,i came up across "Unable to install virtualbox-dkms" though i tried to install the virtualbox-dkms seperately and gone though many stack-overflow solutions but am unable to fix it.

Detailed picture of the issue:
https://ibb.co/dPGY0Rf

**Comment by aquibbaig** [comment]
@Kajol-Kumari Try installing vagrant and doing a `vagrant up` in the vagrant subfolder of this repository

**Comment by imphil** [comment]
You first need to fix your Virtualbox installation. Depending on your distribution, there might be different ways to achieve that. What distribution are you using? You can double-check if things work using the Virtualbox GUI.

**Comment by Kajol-Kumari** [comment]
@imphil  I am using Ubuntu 18.04.3. While running the installation command i am getting an output like https://ibb.co/c3TdypR

And on running "virtualbox --version" i am getting something like https://ibb.co/bFk4TJW.



on reconfiguring as suggested by one of the doc. of stack-exchange i am getting https://ibb.co/0Yjjg5V.

Can you please tell me where exactly is the problem.

**Comment by Kajol-Kumari** [comment]
@aquibbaig I am getting something like this https://ibb.co/hy1gC5d. Though the virtualbox-dkms and headers are already installed but it still saying it to install on runing "VBoxManage --version" as suggested in the terminal.

**Comment by imphil** [comment]
Your VirtualBox installation is broken; this is not a problem in the librecores development setup. Once you fix VirtualBox  you can retry the LibreCores vagrant setup. I cannot really help you debug your setup, but a couple hints to get started:
- Did you install virtualbox from the standard Ubuntu repositories, not from the virtualbox.org repositories or other sources?
- Did you reboot after the last kernel update and before running the VirtualBox driver setup?

Going beyond that you probably need to consult a Ubuntu forum/chat.

**Comment by Kajol-Kumari** [comment]
yes,i understand that the problem is occurring with virtualbox and so trying to install it seperately. But according to the doc "./bootstrap-dev.sh" should have installed all the dependencies and setup as i am using Ubuntu but it's still giving the same error i.e

" Installation of all prerequisites finished.
Start the development VM now? [yN] y
Running vagrant up to setup. This will take some time.
Vagrant failed to initialize at a very early stage:

VirtualBox is complaining that the installation is incomplete. Please
run `VBoxManage --version` to see the error message which should contain
instructions on how to fix this error."

I wonder is it happening with me only or with other Ubuntu users also?

**Comment by Kajol-Kumari** [comment]
The problem was that virtualbox-dkms was not showing installed after running './bootstrap-dev.sh' though it was already installed. So, i reinstalled it using "sudo apt-get install --reinstall virtualbox-dkms" and then a popup appeared where i set the password and the i rebooted and ran "cd vargrant;vagrant up". Got the page on http://librecores.devel/.

Thank you for the guidance.
