### ISSUE TITLE
Ansible failing during installation

### ISSUE THREAD

**Issue by adityabisoi** [librecores/librecores-web#434]
The command ```sudo ./bootstrap-dev.sh``` gives an error - "Ansible failed to complete successfully". Some screenshots are here : 
![Screenshot from 2020-01-04 11-01-58](https://user-images.githubusercontent.com/42573842/71760935-e35d7800-2eea-11ea-964e-f586ab9ca1f1.png)

![Screenshot from 2020-01-04 11-02-19](https://user-images.githubusercontent.com/42573842/71760945-f07a6700-2eea-11ea-9146-49f12a0cf9da.png)

![Screenshot from 2020-01-04 11-02-47](https://user-images.githubusercontent.com/42573842/71760951-f53f1b00-2eea-11ea-9b87-d838ca35ec60.png)

**Comment by Kajol-Kumari** [comment]
Try running the same command without "sudo" in the main repository.
And if it didn't work then use the alternative version of option3 from the docs at https://librecores-web.readthedocs.io/en/latest/devenv/quickstart.html

**Comment by imphil** [comment]
No sudo is required, but that's not where the error comes from.

composer sometimes fails for no obvious reason, please retry, it often works the second time.

**Comment by Kajol-Kumari** [comment]
@imphil I also ran into the same problem but when i ran the command again i am getting something like :"https://ibb.co/kMq2N5v " in the terminal and a blank  page: "https://ibb.co/S6XSspw " on the browser.

**Comment by Kajol-Kumari** [comment]
@imphil  i also got the same error when i ran it for the first tym. But when i ran i for the second time.I was getting https://ibb.co/kMq2N5v in the terminal and a blank page on the http://www.librecores.devel/. 
Then i ran "vagrant provision" as suggested in the terminal and got https://ibb.co/SyvWwT1 and https://ibb.co/G38pwzZ though on runing "ansible --version"
I am getting:
"ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/kajoo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]"

**Comment by adityabisoi** [comment]
@Kajol-Kumari I faced the same issue, as well. I re-installed ansible through apt. Then, executing ```./bootstrap-dev.sh``` again solved the issue.

**Comment by Kajol-Kumari** [comment]
@adityabisoi I have tried reinstalling ansible but still i am getting the same errors and output.
