### ISSUE TITLE
Add bitsbytesgates blog to community

### ISSUE THREAD

**Issue by mballance** [librecores/librecores-web#439]
Hi,
    I'm not sure if this is the best way to contribute a new blog to the community feed. So, please let me know if a different way is preferred.
    I'd like to contribute my blog to the feed. The RSS feed is:
http://bitsbytesgates.blogspot.com/feeds/posts/default?alt=rss

Thanks and Regards,
Matthew

**Comment by olofk** [comment]
Hi @mballance . Thanks for reaching out. We want to have all interesting blogs dealing in FOSSi topics. Think I got it added now but don't remember how the deployment side of the site works. Please reopen if it doesn't appear in the feed within a week or so

**Comment by imphil** [comment]
I just pushed this to production, thanks!
