### ISSUE TITLE
ORCONF: Provide several sample projects

### ISSUE THREAD

**Issue by oleg-nenashev** [librecores/librecores-web#46]
I would like to get several sample projects posted on LibreCores staging. It would be useful for demos of LibreCores CI integration in #45.

Desired projects:
- [ ] wb_sdram_ctrl
- [ ] sockit
- [ ] wb_bfm
- [ ] mor1kx
- [ ] OPTIMSoC (a couple of configurations, for which we need a CI)

**Comment by olofk** [comment]
sockit might be a bit fragile. While it's good to have proper CI for that, I would recommend starting with de0_nano, which is probably the best supported board

**Comment by oleg-nenashev** [comment]
Makes sense.
Requires old quartus images BTW

**Comment by imphil** [comment]
We now have sample projects on staging, as well as real projects in production. Marking this solved.
