### ISSUE TITLE
Use proper search engine

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#47]
Currently we search projects directly in MySQL. For a better search experience, we should move to Apache Solr or similar solutions, which then enable good result ranking, faceted search, etc.

Example implementation in Symfony: Packagist (https://github.com/composer/packagist)

**Comment by berndca** [comment]
How about a [full text search](http://www.w3resource.com/mysql/mysql-full-text-search-functions.php)? 
[librecores.org](https://librecores.org) is a very low traffic site. Apache Solr is an overkill.

**Comment by Agathver** [comment]
How about using an API like algolia instead? Adding solr or elasticseaech will require us to manage another installation. Algolia's free plan will currently serve the site easily and they also offer high volume plans for free to open source projects.

**Comment by wallento** [comment]
I like the idea of Algolia. Due to its very low complexity we should probably use this and make a custom search engine a lower priority for the future if needed.

**Comment by redox** [comment]
Hey @agathver @wallento, Sylvain from Algolia jumping in :) We're happy providing open-source projects extended quotas so should you need more records/operations than our COMMUNITY (free) plan, just [let us know](https://www.algolia.com/for-open-source).

Also, Algolia is now powering the search of Packagist, did you give it a try?

**Comment by wallento** [comment]
Thanks, @redox, also for pointing out that Packagist switched to Algolia too.

**Comment by eliaskousk** [comment]
I also like Algolia since I learned them from their integration in the
official Symfony docs. Let's give it a try.

**Comment by wallento** [comment]
Awesome. I have done the basic setup and will push it to a PR soon. I am not too good at the frontend stuff but have the impression its not too hard to work out. Anyone can have a take on this?

**Comment by agathver** [comment]
@wallento You can assign the frontend work to me

**Comment by wallento** [comment]
Awesome, thanks @agathver!

**Comment by imphil** [comment]
Fixed using Algolia in 550622e1363cdf6b2c6fa564023f8d8ef1799140
