### ISSUE TITLE
Add support of adding projects from organization

### ISSUE THREAD

**Issue by oleg-nenashev** [librecores/librecores-web#48]
As a GitHub user, I want to add project hosted on the external organization (e.g. openrisc/mor1kx). Now I cannot do it from the web interface.

Option 1:
- Add a plain-text field for user/organization name

Option 2:
- Poll user _PUBLIC_ organization membership
- Provide list of organizations
- For the selected organization retrieved list of repositories, to which the user has write access (should be enough to consider him as contributor). Or admin access...

**Comment by imphil** [comment]
I'm not sure I understand this issue correctly. Currently, we don't use the Github APIs but projects can be created using an arbitrary https git URL. So this URL could reference a git repository inside an organization or inside an user namespace.

**Comment by eliaskousk** [comment]
As I understood from our meeting @ orconf we won't use the Github API yet. So I will continue with our own organizations implementation and later on if we need to use the Github API to retrieve the Github organizations of the user we shall re-visit this discussion, correct?

**Comment by imphil** [comment]
@eliaskousk yes, this bug is essentially importing data using the GH API. This is something we don't support for now. However, let's leave this bug open and revisit when it's time to do so.

**Comment by imphil** [comment]
Importing from GH is now possible.
