### ISSUE TITLE
502 Bad Gateway nginx/1.10.3 (Ubuntu)

### ISSUE THREAD

**Issue by patrick-amaru** [librecores/librecores-web#501]
The error 502 Bad Gateway nginx/1.10.3 (Ubuntu) is all I get when I access the site https://www.librecores.org/.
I am on Ubuntu 20.04 with Firefox 103.0.
No idea if this is the right place to report an issue like that, but it is all I could find.

**Comment by GaLaKtIkUs** [comment]
I'm facing the same problem. This is a problem from their side. The web service running behind nginx is not running or crashing (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502). Perhaps they just shutdown their server?

Also I tried contacting them by email and through twitter but unfortunately didn't get any answer.

Hope that they are just preparing some cool update )

Best regards

**Comment by imphil** [comment]
Thanks for reporting this issue (and yes, here's the right place for such reports). It was a server-side issue, which is now resolved.

**Comment by GaLaKtIkUs** [comment]
Today I'm having the same issue.
