### ISSUE TITLE
Disallow certain user and project names

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#51]
To avoid naming clashes in the URL, prevent all user/org names that we use as regular URL: "unassigned", "new". others?

**Comment by olofk** [comment]
Is the plan still to use full VLNV naming, with Vendor and Library optionally being left empty?

**Comment by imphil** [comment]
@olofk it's independent of this issue, but that's my current throught:
Currently, librecores lists "projects". Inside these projects (i.e. as another subhierarchy), there can be cores and systems as fusesoc knows them. The plan is to scan the git repo for core and system files, and based on that automatically list cores/systems as part of a project. To avoid name clashes, as discussed earlier, we'll most likely enforce that vendor:library == org_or_user/project, leaving the last component (name) available to be used inside the project.
