### ISSUE TITLE
Fixtures: Switch from SQL dump to proper fixtures

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#55]
During development, we want to use test-data inside the database which allows us to quickly test features. Fixtures insert this kind of data into the DB through the actual objects (entities) which are used in our business layer.

Right now, we "cheat" by inserting a SQL-dump directly into the DB (this one: https://github.com/librecores/librecores-web/blob/master/sql/dev_fixtures_site.sql). This approach breaks whenever the entities change. So we should switch to proper fixtures, as described in http://symfony.com/doc/current/bundles/DoctrineFixturesBundle/index.html.

Tasks here:
* Get the fixture system working by integrating the correct bundle.
* Add fixtures which add
  * at least one test user
  * at least one organization
  * at least two test projects
* document the test user and passwords in the development documentation (doc/)
* (optional, just as Philipp otherwise) Adjust the Ansible deployment code to execute the fixtures and not insert the DB dump.

This bug has been marked as a "good first bug". If you're interested in working on it, have a look at the developer documentation at http://librecores-web.readthedocs.io/en/latest/ and comment on this bug or contact the listed mentor for more details. The mentor will be available to help you complete this task.

Mentor: @imphil
Required Skills: PHP, Symfony, a bit of Doctrine/database knowledge

**Comment by eliaskousk** [comment]
I can take care of this... rather boring task! :P
