### ISSUE TITLE
Tell people how to contribute on the site itself

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#63]
mention mailing list, github, etc.

**Comment by oleg-nenashev** [comment]
And maybe a common "Fork me on GitHub" badge. But "Fork" was always vague in this statement IMHO

**Comment by imphil** [comment]
Documented in d59d36736ee6ee7a7905f8ac0ae89285ee1e04d4 on http://librecores-web.readthedocs.io/en/latest/contributing.html and linked in various places in  d9a1bfff2a8f45b29ffeffaa0d37e382cb58ae32 and 5c237aef6bfd3336ecbaf624471941ce714b8233
