### ISSUE TITLE
Enable compression in nginx

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#66]
Report from google pagespeed:

Compressing resources with gzip or deflate can reduce the number of bytes sent over the network.
Enable compression for the following resources to reduce their transfer size by 325.5KiB (74% reduction).

```
Compressing https://www.librecores.org/css/app.css could save 159KiB (83% reduction).
Compressing https://www.librecores.org/js/app_body.js could save 139.4KiB (68% reduction).
Compressing https://www.librecores.org/img/home-cat-3.svg could save 6.9KiB (69% reduction).
Compressing https://www.librecores.org/img/home-cat-1.svg could save 5.4KiB (69% reduction).
Compressing https://www.librecores.org/img/home-cat-5.svg could save 4.1KiB (63% reduction).
Compressing https://www.librecores.org/img/home-cat-2.svg could save 3.9KiB (68% reduction).
Compressing https://www.librecores.org/img/home-cat-4.svg could save 3.4KiB (67% reduction).
Compressing https://www.librecores.org/img/logo_small.svg could save 3.4KiB (70% reduction).
```

**Comment by Agathver** [comment]
This looks like we need to add assetic filters for compressing and optimizing CSS, JS and SVG. http://symfony.com/doc/current/assetic/uglifyjs.html

**Comment by imphil** [comment]
Another option is presented in #67 I'm not yet sure which one is easier to use/gives better results.

**Comment by Agathver** [comment]
#67 explores HTTP compression. It is a protocol level lossless compression using gzip/bzip2 or any such algorithms. Here is a relevant article:
- https://developers.google.com/speed/docs/insights/EnableCompression

Here I mentioned about, asset minification i.e, removal of unnecessary characters, whitespace etc. something like these:
- https://developers.google.com/speed/docs/insights/MinifyResources
- https://developers.google.com/speed/articles/compressing-javascript
- https://developers.google.com/speed/docs/insights/OptimizeImages

I'll look into the PageSpeed Insights results and report what more can be done

**Comment by imphil** [comment]
In the end, compression on protocol level should be similarly effective as removing whitespace before. Same goes for shorter variable names and the like -- in the end, that's just what run-length encoding is being made for.

**Comment by Agathver** [comment]
I was trying to add compression settings to `nginx.conf`, but could not find the template for it

**Comment by Agathver** [comment]
With https://github.com/KonstantinKuklin/AsseticStaticGzipBundle and http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html we can save server CPU time by pre-compressing static resources.

**Comment by imphil** [comment]
With #149 and the follow-up in f2eeda493e96a84cb4a33bfba555d65793eb353a we get a Google Speedtest result of 87 / 100 for desktop, resolving this issue. Thanks @Agathver!
