### ISSUE TITLE
Login with GitHub and Google did not work for me

### ISSUE THREAD

**Issue by kasbah** [librecores/librecores-web#77]
Just tried to register/login with GitHub and then Google but it doesn't work. This is with Firefox 49 on Ubuntu and all sorts of extensions enabled (e.g. Privacy Badger and uBlock Origin).

EDIT: Just tried in new Firefox profile without extensions and also in Chrome and Chromium without success. The page always re-directs back to the login form. I don't see any errors or messages on the Javascript console.

**Comment by imphil** [comment]
Hi and sorry it took so long, I've identified an issue with the server installation that should be fixed now. I'm able to login again. Could you please try again and let me know if the issue is resolved for you?

**Comment by kasbah** [comment]
Works for me with GitHub! Thanks!
