### ISSUE TITLE
Username validation bug

### ISSUE THREAD

**Issue by eliaskousk** [librecores/librecores-web#81]
I identified a bug on the username validator and fixed it on master so please check it and push it to production when you see this.  0104e150a9d18b4542907eccb94789d8797f2e1b

I also removed a redundant uniqueness check for usernames since it is already handled by the user bundle. 1132e3f1cbbda624a62a78693f05487371d685f0

On a sidenote, is there a recommended way to notify the need for a push to production? I didn't know if you prefer PRs for such small changes / bug fixes that need pushing to production so I just pushed to master and opened this issue.

**Comment by eliaskousk** [comment]
I saw that staging or production not updated since Orconf so this also answers my above question. I suppose that we will push there only after a substantial amount of work is done and that work is reviewed and tested locally. (until now I thought Philipp pushed regularly there).

**Comment by imphil** [comment]
@eliaskousk thanks for the patch. I'll waited pushing out the changes until we have a sufficiently working org feature, currently this in a bit of a half-working state that I don't want to be published just yet.
