### ISSUE TITLE
Better handle huge repositories in UpdateProjectInformation

### ISSUE THREAD

**Issue by imphil** [librecores/librecores-web#85]
Example: https://github.com/krevanth/ZAP is more than 300 MB and cannot be cloned in 3 minutes. We probably should do a couple of things for such repos: 

- do a flat clone to get the README and LICENSE file.
- re-use a clone made once with much higher timeout (also look into Process::setIdleTimeout()) and update that periodically to get the latest repo statistics.
- other clone options to get only essential parts and not the full repo data which we in the end don't care about?

**Comment by oleg-nenashev** [comment]
Maybe there is no need to clone repositories at all (in the case of projects on GitHub). It is possible to use GitHub API to get file listings and then to download files directly

**Comment by berndca** [comment]
Please note that the archive for this repo https://github.com/krevanth/ZAP/archive/master.zip is less than 1MB and it downloads in a few seconds. Of course this will only work when the "download as archive" option is available.

**Comment by imphil** [comment]
We're now using a flat clone, this solved the issue for now. Everything else will involve the API integration, which is coming in the future (and different issues).
