### ISSUE TITLE
vagrant up hangs after librecores: SSH auth method private key

### ISSUE THREAD

**Issue by berndca** [librecores/librecores-web#95]
I ran bootstrap-dev.sh and used the default credentials (ansible/secrets.dist/dev-vagrant.secrets.yml).

I added v.gui = true to the vrtual box environment

The virtualbox window shows a few messages:

lvmetad is not active yet, using direct activation during sysinit (2x)

Scanning for Btrfs filesystems
/dev/mapper/vagrant--vg-root: clean ...
6.9... piix4_smbus 000:00:07.0: SMBus base address uninitialized - upgrade BIOS or use force_addr=0xadddr
7.01... intel_rapl: no valid rapl domains found in package 0 (2x)
[*** ] A start job is running for Raise network interfaces (5min 3s / 5min 3s)

This times out after 5min and shows a login prompt. After logging in I ran ifconfig and got only 
two network interfaces: enp0s3 and lo. There appears to be a networking problem.

What am I missing?

PS: Host OS is Ubuntu 16.04.1 desktop.

**Comment by eliaskousk** [comment]
Hi,

I've seen this happen before with the bento/ubuntu-16.04 box image v.2.3.0.
Thus we stayed to 2.2.9 which works fine but now I see in the Vagrantfile
that Philipp has recently upgraded to v2.3.1 which probably has the same
networking issues as v2.3.0. Change the 'config.vm.box_version' in the
Vagrantfile to 2.2.9 and you should be fine. The commit can wait until
tomorrow (its almost 5AM in Greece now!)

Best regards,
Elias

**Comment by berndca** [comment]
Thanks for the quick response. I changed line 7 of the Vagrantfile to

config.vm.box_version = '2.2.9'

However the symptoms remain. This did not have seemed to make a difference.

**Comment by imphil** [comment]
I'll try to reproduce this, I already have an idea.

**Comment by imphil** [comment]
@berndca I've been able to reproduce your problem and pushed a fix. To try it, destroy your VM and recreate it:

~~~
cd vagrant
vagrant destroy
vagrant up
~~~

**Comment by berndca** [comment]
Thanks, it's working now.
