### ISSUE TITLE
fatal: [librecores]: FAILED! => {"changed": true, "cmd": ["composer", "install"]

### ISSUE THREAD

**Issue by berndca** [librecores/librecores-web#98]
I was trying to set up the dev environment for the latest state of master. Unfortunately this did not work. I tried both vm_box_versions 2.3.1 and 2.2.9.

**Comment by imphil** [comment]
Hm, that's an error of Ansible during provisioning. The box should be OK.
Usually composer takes quite some time to get all dependencies and might fail if your internet connection was interrupted or something like this.

Just go into the vagrant folder, and re-try provisioning.

~~~
cd vagrant
vagrant provision
~~~

If this doesn't help, try 
~~~
vagrant destroy
vagrant up
~~~

again. I don't see the issue here, so I'm strongly assuming something in your setup ... So let's make first sure it's not intermittent.

**Comment by berndca** [comment]
I tried vagrant provision first. This did not work, so I went ahead with vagrant destroy/up. It failed with the same error message again. Internet should not be an issue (wired connection to ADSL). Here is the complete error message:

fatal: [librecores]: FAILED! => {"changed": true, "cmd": ["composer", "install"], "delta": "0:00:00.292500", "end": "2017-01-27 21:53:49.432517", "failed": true, "rc": 1, "start": "2017-01-27 21:53:49.140017", "stderr": "\n                                                                                                                                                                                                                            \n  [Composer\\Repository\\InvalidRepositoryException]                                                                                                                                                                          \n  Invalid repository data in /var/www/lc/site/vendor/composer/installed.json, packages could not be loaded: [Seld\\JsonLint\\ParsingException] \"/var/www/lc/site/vendor/composer/installed.json\" does not contain valid JSON  \n  Parse error on line 1:                                                                                                                                                                                                    \n  ^                                                                                                                                                                                                                         \n  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['                                                                                                                                                    \n                                                                                                                                                                                                                            ", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by imphil** [comment]
It seems that the file `site/vendor/composer/installed.json` somehow got corrupted. This directory is mounted from your source tree into the VM, so a vagrant destroy/up won't get this fixed. Please try the following on your host machine:

~~~
mv site/vendor site/vendor-notused
cd vagrant
vagrant provision
~~~

It should re-run composer and get the `vendor` directory back.

**Comment by berndca** [comment]
I copied the site/vendor/composer/installed.json from a previous run and it appears to work now.

Thanks, Bernd
